name: Deploy Pages
on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install Dependencies
        run: npm ci
      - name: Build Pages
        run: npm run docs:build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: .vitepress/dist
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: macos-latest
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4